Add a basic README
everypolitician/field_serializer pull request #11
Opened 2016-10-28 17:15 UTC by chrismytton

Fill out a basic README.

Fixes #1 

# Notes to reviewer

I struggled a bit to come up with a decent description of this gem. I'm not sure if that's because it's not solving a well enough defined problem or if it's just a bit late on a Friday but any suggestions for improvements are welcome!

2016-10-28 17:15 UTC, chrismytton commented
@tmtmtmtm 👀

2016-11-01 09:09 UTC, tmtmtmtm commented on README.md
> +serialized in the `#to_h` method.
My main comment here is that this is only really explaining the _what_, rather than the _why_.

2016-11-04 09:53 UTC, chrismytton commented on README.md
> +serialized in the `#to_h` method.
Yep, good point! I've added a few more words on why we built it and how we're using it.

2016-11-07 12:32 UTC, tmtmtmtm requested changes
Tiny typo, and I suspect we're going to want to tweak this considerably over time, but it's definitely an improvement over the existing README, so otherwise 👍

2016-11-07 12:32 UTC, tmtmtmtm commented on README.md
> +are using this library in our scrapers to make them more declaritive. It allows
typo: declaritive → declarative

2016-11-07 15:45 UTC, chrismytton commented on README.md
> +are using this library in our scrapers to make them more declaritive. It allows
Oops! Fixed in https://github.com/everypolitician/field_serializer/pull/11/commits/be28beb9eff91aabea5872422f837cb62f0e6c95.

2016-11-08 06:20 UTC, tmtmtmtm approved these changes

2016-11-08 06:20 UTC, merged